# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.1/siti-cli_2.0.1_darwin_amd64.tar.gz"
      sha256 "49fd63d1aed8b969304b73c5349de3581a68e010c868f018b45355ddfce2ceed"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.1/siti-cli_2.0.1_darwin_arm64.tar.gz"
      sha256 "1106bc6b3b28b3f2a7429e893615b53b43600936a440f3923b0d4e06e39ae609"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.1/siti-cli_2.0.1_linux_amd64.tar.gz"
      sha256 "85171962e912655c728bd65b18c67b93a5433ab38e28bacf0fc9a172e1e9c6b2"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.1/siti-cli_2.0.1_linux_arm64.tar.gz"
      sha256 "dd171842ce3e24b66edd1ecd5403c904a75e6ef7e6f9ec758814404e598144fc"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        echo 'eval "$(siti init zsh)"' >> ~/.zshrc
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
